student(kasper).
student(jonas).
student(martin).
student(jacob).
student(alex).
student(andreas).
student(julie).
student(kathrine).
student(mette).
student(lars).
student(henrik).
student(morten).
student(bent).
student(abdi).
student(hassan).
student(tine).
student(josefine).
student(amalie).
student(sine).
student(cecilie).
