takes(alex, matematik).
takes(alex, fysik).
takes(alex, so).
takes(andreas, dansk).
takes(andreas, so).
takes(andreas, fysik).
takes(jonas, fysik).
takes(jonas, engelsk).
takes(jonas, matematik).
takes(kasper, dansk).
takes(kasper, so).
takes(kasper, engelsk).
takes(martin, matematik).
takes(martin, engelsk).
takes(martin, dansk).
takes(jacob, so).
takes(jacob, dansk).
takes(jacob, fysik).
takes(julie, atletik).
takes(julie, fysik).
takes(julie, musik).
takes(julie, samfundsfag).
takes(kathrine, musik).
takes(kathrine, elektronik).
takes(mette, dansk).
takes(mette, engelsk).
takes(mette, samfundsfag).
takes(lars, elektronik).
takes(henrik, musik).
takes(henrik, fysik).
takes(morten, kemi).
takes(morten, biologi).
takes(morten, matematik).
takes(bent, so).
takes(bent, matematik).
takes(abdi, atletik).
takes(abdi, dansk).
takes(hassan, dansk).
takes(hassan, engelsk).
takes(hassan, samfundsfag).
takes(hassan, musik).
takes(hassan, elektronik).
takes(tine, dansk).
takes(tine, engelsk).
takes(tine, samfundsfag).
takes(tine, musik).
takes(josefine, musik).
takes(josefine, engelsk).
takes(amalie, engelsk).
takes(amalie, dansk).
takes(sine, fysik).
takes(sine, kemi).
takes(sine, biologi).
takes(sine, matematik).
takes(cecilie, atletik).
